name: MyFA
options:
  bundleIdPrefix: com.finclip.chatkit
  deploymentTarget:
    iOS: "16.0"

schemes:
  MyFA:
    build:
      targets:
        MyFA: all
    run:
      config: Debug

packages:
  FinClipChatKit:
    url: https://github.com/Geeksfino/finclip-chatkit.git
    from: 0.9.2
  finclip-neuron:
    url: https://github.com/Geeksfino/finclip-neuron.git
    branch: main-swift6_0

targets:
  MyFA:
    type: application
    platform: iOS
    sources:
      - path: App/App
      - path: App/Extensions
      - path: App/ViewControllers
      - path: App/Models
      - path: App/Services
      - path: App/Components
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.finclip.chatkit.myfa
      PRODUCT_NAME: MyFA
      INFOPLIST_KEY_CFBundleDisplayName: MyFA
      INFOPLIST_FILE: App/App/Info.plist
      ENABLE_BITCODE: NO
      DEVELOPMENT_LANGUAGE: en
      INFOPLIST_KEY_CFBundleLocalizations: en, zh-Hans
      CODE_SIGN_STYLE: Automatic
      FRAMEWORK_SEARCH_PATHS[sdk=iphoneos*]: $(inherited) $(BUILT_PRODUCTS_DIR)/FinClipChatKit.framework/Frameworks
      FRAMEWORK_SEARCH_PATHS[sdk=iphonesimulator*]: $(inherited) $(BUILT_PRODUCTS_DIR)/FinClipChatKit.framework/Frameworks
      LD_RUNPATH_SEARCH_PATHS: $(inherited) @executable_path/Frameworks @loader_path/Frameworks @loader_path/Frameworks/FinClipChatKit.framework/Frameworks
      SWIFT_INCLUDE_PATHS[sdk=iphoneos*]: $(inherited) $(BUILT_PRODUCTS_DIR)/FinClipChatKit.framework/Frameworks
      SWIFT_INCLUDE_PATHS[sdk=iphonesimulator*]: $(inherited) $(BUILT_PRODUCTS_DIR)/FinClipChatKit.framework/Frameworks
    dependencies:
      - product: FinClipChatKit
        package: FinClipChatKit
      - product: NeuronKit
        package: finclip-neuron
      - product: SandboxSDK
        package: finclip-neuron  
      - product: convstorelib
        package: finclip-neuron
      - product: ConvoUI
        package: finclip-neuron
    postbuildScripts:
      - name: Sign Nested Frameworks
        shell: /bin/sh
        inputFiles:
          - $(TARGET_BUILD_DIR)/$(FRAMEWORKS_FOLDER_PATH)/FinClipChatKit.framework/Frameworks
        script: |
          # Only run for device builds, not simulator
          if [ "${PLATFORM_NAME}" != "iphonesimulator" ]; then
            FRAMEWORK_DIR="${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/FinClipChatKit.framework/Frameworks"
            if [ -d "${FRAMEWORK_DIR}" ]; then
              echo "Signing nested frameworks in ${FRAMEWORK_DIR}"
              find "${FRAMEWORK_DIR}" -type d -name "*.framework" -print0 | while IFS= read -r -d '' FRAME; do
                if [ -d "${FRAME}" ]; then
                  echo "Signing ${FRAME}"
                  /usr/bin/codesign --force --sign "${EXPANDED_CODE_SIGN_IDENTITY}" --preserve-metadata=identifier,entitlements "${FRAME}" || echo "Warning: Failed to sign ${FRAME}"
                fi
              done
              echo "Finished signing nested frameworks"
            else
              echo "Note: FinClipChatKit nested frameworks directory not found at ${FRAMEWORK_DIR}"
            fi
          else
            echo "Skipping nested framework signing for simulator build"
          fi

